name: wildfire-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - rasterio
  - rioxarray
  - pyproj
  - ipykernel
  - pystac-client
  - planetary-computer
  - stackstac
  - dask
